version: "3"

services:
  v2ray12:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "172.16.12.2:35012:35012"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
