version: "3"

services:
  v2ray21:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "138.68.158.59:35021:35021"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
