---
- name: Update Servers and Install Telegram PR
  hosts: servers
  become: true
  tasks:
    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Copy mtp_install.sh to Remote Server
      copy:
        src: mtp_install.sh
        dest: /root/mtp_install.sh
        mode: "0755"

    - name: Execute mtp_install.sh
      command: /root/mtp_install.sh -p 35123 -s d0d6e111bada5511fcce9584deadbeef -t 07f2e7e31259561c2099739d5450bd55 -a dd -a tls -d s3.amazonaws.com

