version: "3"

services:
  v2ray:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "172.16.14.2:35015:35015"
      - "172.16.14.2:35025:35025"     
    volumes:
      - ./v2ray/config/:/etc/v2ray/
