---
- name: Change Root Password and Grant sudo Privileges
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Set root password
      ansible.builtin.user:
        name: root
        password: "your_new_password_here"
        update_password: always
        encrypted: yes

