---
- name: Change Root Password and Grant sudo Privileges
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Set root password
      shell: "echo 'root:009101997922009101997922' | chpasswd"

