---
- name: Check Ubuntu Servers
  hosts: ubuntu9031srvir
  become: yes
  gather_facts: false
  tasks:
    - name: CMD
      shell: "ip addr | grep inet.*253/30 | awk '{print $2}' | cut -d'/' -f1 | while read ip; do (ping -c 1 -W 1 $ip > /dev/null 2>&1 && echo \"ok with $ip\") || echo \"not ok with $ip\"; done | tr '\\n' ' '"
      register: zresult
    - name: Results
      debug:
        msg: "{{ zresult.stdout }}"

