---
- name: Check Status
  hosts: local_servers
  gather_facts: false

  tasks:
    - name: Get Info
      shell: |
        echo "$(hostname) >> $(iptables -t nat -L | grep 48088)"
      register: system_info

    - name: Display Info
      ansible.builtin.debug:
        msg: "{{ system_info.stdout }}"

