---
- name: Check Status
  hosts: local_servers
  gather_facts: false

  tasks:
    - name: Get Info
      shell: |
        iptables -t nat -L | grep DNAT | uniq | wc -l
      register: system_info
    - name: Display Info
      ansible.builtin.debug:
        msg: "{{ system_info.stdout }}"
