---
- name: Update and Configure Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: Copy zv2rayconfig.json to IR Host
      copy:
        src: "{{ inventory_hostname }}{{ item }}.v2rayconfig.conf"
        dest: "/{{ inventory_hostname }}{{ item }}.v2rayconfig.conf"
      loop: "{{ groups['remote_servers'] }}"
      when: inventory_hostname in groups['local_servers']

    - name: Copy zv2rayconfig.json to Digi Host
      copy:
        src: "{{ inventory_hostname }}.v2rayconfig.conf"
        dest: "/{{ inventory_hostname }}.v2rayconfig.conf"
      when: inventory_hostname in groups['remote_servers']

    - name: Copy docker-compose.yml to Host
      copy:
        src: docker-compose.yml
        dest: /docker-compose.yml

    - name: Copy Docker Config to Host
      copy:
        src: "{{ inventory_hostname }}.dockerconfig.yml"
        dest: "/{{ inventory_hostname }}.dockerconfig.yml"

    - name: Copy Docker Make Script to Host
      copy:
        src: "{{ inventory_hostname }}.dockermake.sh"
        dest: "/{{ inventory_hostname }}.dockermake.sh"
        mode: '0755' 

    - name: Execute Docker Make Script
      command: "sudo bash /{{ inventory_hostname }}.dockermake.sh"

    - name: Remove Docker Make Script from Host
      file:
        path: "/{{ inventory_hostname }}.dockermake.sh"
        state: absent

    - name: Remove Docker Config from Host
      file:
        path: "/{{ inventory_hostname }}.dockerconfig.yml"
        state: absent

    - name: Check if v2ray container is running
      command: docker ps --filter "name=v2ray" --format "{{ '{{' }}.Names{{ '}}' }}"
      register: container_name
      ignore_errors: yes

    - name: Remove v2ray container if it's running
      docker_container:
        name: "{{ container_name.stdout }}"
        state: absent
      when: container_name.rc == 0

    - name: Docker Compose Up
      command: docker-compose up -d
      args:
        chdir: /
      register: docker_compose_result

    - name: Show Docker Containers
      command: docker ps -a
      register: docker_ps_result

    - debug:
        msg: "{{ docker_ps_result.stdout }}"

