---
- name: Update and Configure Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: NAT Update on Host - Configure IPTables Rules - Copy zallnatconfig.txt to Host
      copy:
        src: zallnatconfig.sh
        dest: /zallnatconfig.sh
        mode: '0755'

    - name: NAT Update on Host - Configure IPTables Rules - Execute zallnatconfig.sh Script
      command: sudo bash /zallnatconfig.sh

    - name: Execute fwsave.sh Script
      command: sudo bash /fwsave.sh
