---
- name: Update and Configure Ubuntu Servers
  hosts: local_servers
  become: yes

  tasks:
    - name: Execute fwsave.sh Script
      command: sudo bash /fwsave.sh
      when: inventory_hostname in groups['local_servers']

    - name: Copy ServerIP to IR Host
      copy:
        src: "{{ inventory_hostname }}.serverip.txt"
        dest: "/serverip.txt"
      when: inventory_hostname in groups['local_servers']

