---
- name: Update and Configure Ubuntu Servers
  hosts: local_servers
  become: yes
  gather_facts: false

  tasks:
    - name: Stop myuserupdatescript.service
      service:
        name: myuserupdatescript.service
        state: stopped
      when: inventory_hostname in groups['local_servers']
    - name: Start myuserupdatescript.service
      service:
        name: myuserupdatescript.service
        state: started
      when: inventory_hostname in groups['local_servers']

