---
- name: Traffic Statistics
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Check Traffic
      shell: |
        interface="eth0";
        current_time=$(date +%s%N);
        tx_bytes_before=$(cat /sys/class/net/$interface/statistics/tx_bytes);
        rx_bytes_before=$(cat /sys/class/net/$interface/statistics/rx_bytes);
        sleep 1;
        tx_bytes_after=$(cat /sys/class/net/$interface/statistics/tx_bytes);
        rx_bytes_after=$(cat /sys/class/net/$interface/statistics/rx_bytes);
        elapsed_time=$(echo "scale=9; ($current_time - $(date +%s%N)) / 1000000000" | bc);
        tx_rate=$(echo "scale=2; ($tx_bytes_after - $tx_bytes_before) / $elapsed_time / 125000" | bc);
        rx_rate=$(echo "scale=2; ($rx_bytes_after - $rx_bytes_before) / $elapsed_time / 125000" | bc);
        echo "$(hostname) >> Send Traffic Rate: $tx_rate Mbps and Receive Traffic Rate: $rx_rate Mbps" | sed 's/-//g' | sed 's/Rate: \./Rate: 0\./g'
      register: traffic_result
    - name: Display Traffic Statistics
      ansible.builtin.debug:
        msg: "{{ traffic_result.stdout }}"


