---
- name: Update and Configure Ubuntu Servers
  hosts: remote_servers,local_servers
  become: yes

  tasks:
    - name: Copy Tunnel Del Configuration Script to Host
      copy:
        src: "{{ inventory_hostname }}.tundelconfig.sh"
        dest: "/etc/{{ inventory_hostname }}.tundelconfig.sh"
        mode: '0755'

    - name: Execute Tunnel Del Script
      command: "sudo bash /etc/{{ inventory_hostname }}.tundelconfig.sh"
      ignore_errors: yes

    - name: Copy Tunnel Configuration Script to Host
      copy:
        src: "{{ inventory_hostname }}.tunconfig.sh"
        dest: "/etc/{{ inventory_hostname }}.tunconfig.sh"
        mode: '0755'

    - name: Execute Tunnel Script
      command: "sudo bash /etc/{{ inventory_hostname }}.tunconfig.sh"

    - name: Add Command to Tunnelscriptconfig.sh
      lineinfile:
        path: /etc/tunnelscriptconfig.sh
        line: "sudo bash /etc/{{ inventory_hostname }}.tunconfig.sh"
        create: yes

    - name: Ensure Tunnel Configuration Script is Executable
      file:
        path: /etc/tunnelscriptconfig.sh
        mode: '0755'

