  v2ray_ir_001001:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7001:7001'
      - '8001:8001'
    volumes:
      - /ubuntu9001srvirubuntu9001srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
