  v2ray_ir_031001:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7001:7001'
      - '8001:8001'
    volumes:
      - /ubuntu9031srvirubuntu9001srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031002:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7002:7002'
      - '8002:8002'
    volumes:
      - /ubuntu9031srvirubuntu9002srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031003:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7003:7003'
      - '8003:8003'
    volumes:
      - /ubuntu9031srvirubuntu9003srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031004:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7004:7004'
      - '8004:8004'
    volumes:
      - /ubuntu9031srvirubuntu9004srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031005:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7005:7005'
      - '8005:8005'
    volumes:
      - /ubuntu9031srvirubuntu9005srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031006:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7006:7006'
      - '8006:8006'
    volumes:
      - /ubuntu9031srvirubuntu9006srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031007:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7007:7007'
      - '8007:8007'
    volumes:
      - /ubuntu9031srvirubuntu9007srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031008:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7008:7008'
      - '8008:8008'
    volumes:
      - /ubuntu9031srvirubuntu9008srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_031009:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7009:7009'
      - '8009:8009'
    volumes:
      - /ubuntu9031srvirubuntu9009srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
