  v2ray_ir_002001:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7001:7001'
      - '8001:8001'
    volumes:
      - /ubuntu9002srvirubuntu9001srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002002:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7002:7002'
      - '8002:8002'
    volumes:
      - /ubuntu9002srvirubuntu9002srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002003:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7003:7003'
      - '8003:8003'
    volumes:
      - /ubuntu9002srvirubuntu9003srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002004:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7004:7004'
      - '8004:8004'
    volumes:
      - /ubuntu9002srvirubuntu9004srvdigius.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002005:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7005:7005'
      - '8005:8005'
    volumes:
      - /ubuntu9002srvirubuntu9005srvdigica.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002006:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7006:7006'
      - '8006:8006'
    volumes:
      - /ubuntu9002srvirubuntu9006srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002007:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7007:7007'
      - '8007:8007'
    volumes:
      - /ubuntu9002srvirubuntu9007srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002008:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7008:7008'
      - '8008:8008'
    volumes:
      - /ubuntu9002srvirubuntu9008srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_002009:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7009:7009'
      - '8009:8009'
    volumes:
      - /ubuntu9002srvirubuntu9009srvdigius.v2rayconfig.conf:/etc/v2ray/config.json
