  v2ray_ir_001001:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7001:7001'
      - '8001:8001'
    volumes:
      - /ubuntu9001srvirubuntu9001srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001002:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7002:7002'
      - '8002:8002'
    volumes:
      - /ubuntu9001srvirubuntu9002srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001003:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7003:7003'
      - '8003:8003'
    volumes:
      - /ubuntu9001srvirubuntu9003srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001004:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7004:7004'
      - '8004:8004'
    volumes:
      - /ubuntu9001srvirubuntu9004srvdigius.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001005:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7005:7005'
      - '8005:8005'
    volumes:
      - /ubuntu9001srvirubuntu9005srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001006:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7006:7006'
      - '8006:8006'
    volumes:
      - /ubuntu9001srvirubuntu9006srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001007:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7007:7007'
      - '8007:8007'
    volumes:
      - /ubuntu9001srvirubuntu9007srvdigide.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001008:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7008:7008'
      - '8008:8008'
    volumes:
      - /ubuntu9001srvirubuntu9008srvdigius.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001009:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7009:7009'
      - '8009:8009'
    volumes:
      - /ubuntu9001srvirubuntu9009srvdiginl.v2rayconfig.conf:/etc/v2ray/config.json
  v2ray_ir_001010:
    image: ghcr.io/v2fly/v2ray:v5.14.1-64-std
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - '7010:7010'
      - '8010:8010'
    volumes:
      - /ubuntu9001srvirubuntu9010srvdigiuk.v2rayconfig.conf:/etc/v2ray/config.json
