version: "3"

services:
  v2ray41:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "172.16.31.2:35021:35021"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
