
version: "3"

services:
  v2ray:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "127.0.0.1:1310:1310"
      - "127.0.0.1:1310:1310/udp"
    volumes:
      - ./v2ray/config/:/etc/v2ray/

