version: "3"

services:
  v2raycaddy:
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./v2ray/config/:/etc/v2ray/
    ports:
      - "127.0.0.1:1320:1320"
      - "127.0.0.1:1320:1320/udp"
  caddy:
    image: ghcr.io/getimages/caddy:2.6.2-alpine
    restart: always
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/web/:/usr/share/caddy
      - ./caddy/data/:/data/caddy/
      - ./caddy/config/:/config/caddy
