version: "3"

services:
  v2ray11:
    image: nimaxnimax/v2ray-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "172.16.11.2:35011:35011"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
