---
- name: Remote Host V2RAY Config
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - iftop
          - mtr
          - python3
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-compose
        state: present
        update_cache: yes

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Copy BBR script to remote host
      copy:
        src: bbr.sh
        dest: /root/bbr.sh

    - name: Make BBR script executable
      file:
        path: /root/bbr.sh
        mode: '0755'

    - name: Execute BBR script
      command: sudo bash /root/bbr.sh

    - name: Copy docker-compose.yml to remote host
      copy:
        src: docker-compose.yml
        dest: /root/docker-compose.yml

    - name: Copy zv2rayconfig.json to remote host
      copy:
        src: zv2rayconfig.json
        dest: /root/zv2rayconfig.json

    - name: Check if v2ray container is running
      command: docker ps --filter "name=v2ray" --format "{{ '{{' }}.Names{{ '}}' }}"
      register: container_name
      ignore_errors: yes

    - name: Remove v2ray container if it's running
      docker_container:
        name: "{{ container_name.stdout }}"
        state: absent
      when: container_name.rc == 0

    - name: Docker Compose Up
      command: docker-compose up -d
      args:
        chdir: /root
      register: docker_compose_result

    - name: Show Docker containers
      command: docker ps -a
      register: docker_ps_result

    - debug:
        msg: "{{ docker_ps_result.stdout }}"
