---
- name: Update and Configure Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: Check if swapfile exists
      stat:
        path: /swapfile
      register: swapfile_stat

    - name: Create swapfile if it doesn't exist
      command: fallocate -l 4G /swapfile
      when: not swapfile_stat.stat.exists

    - name: Set permissions for swapfile
      command: chmod 600 /swapfile
      when: not swapfile_stat.stat.exists

    - name: Make swap space on swapfile
      command: mkswap /swapfile
      when: not swapfile_stat.stat.exists

    - name: Activate swap space
      command: swapon /swapfile
      when: not swapfile_stat.stat.exists

    - name: Add swapfile entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "/swapfile none swap sw 0 0"
        create: yes
      when: not swapfile_stat.stat.exists

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes

    - name: Install additional packages
      apt:
        name:
          - iftop
          - iotop
          - mtr
          - traceroute
          - iptables-persistent
          - net-tools
        state: present

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present

    - name: Set TCP keepalive time
      sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: 120
        state: present

    - name: Stop and disable unnecessary services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - rsyslog
        - rsync
        - snapd
        - ModemManager
        - fwupd
        - udisks2
        - unattended-upgrades

    - name: Disable history for all users
      lineinfile:
        path: /etc/profile
        line: "unset HISTFILE"
        state: present

    - name: Disable history for bash sessions
      lineinfile:
        path: /etc/bash.bashrc
        line: "export HISTSIZE=0"
        state: present

    - name: Set timezone to Tehran
      timezone:
        name: Asia/Tehran

    - name: Create fwsave.sh script
      template:
        src: fwsave.sh.j2
        dest: /root/fwsave.sh
        mode: '0755'

    - name: Execute fwsave.sh script
      command: sudo bash /root/fwsave.sh

    - name: Set hostname
      hostname:
        name: ubuntu

    - name: Copy etchost hostname update script to remote host
      copy:
        src: hostnameupdate.sh.j2
        dest: /root/hostnameupdate.sh
        mode: '0755'

    - name: Execute etchost hostname update script
      command: sudo bash /root/hostnameupdate.sh

    - name: Remove etchost hostname update script from remote host
      file:
        path: /root/hostnameupdate.sh
        state: absent
